# spring.application.name=mongojava

server:
  port: 8888

spring:
  data:
    mongodb:
      uri: "mongodb+srv://admin:admin@mongodb.pscbrmg.mongodb.net/?retryWrites=true&w=majority&appName=MongoDB"
      database: "MongoDB"
      port: 27017
    #   username: "admin"
    #   password: "admin"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      topic-java: topic-java

logging:
  level:
    com.mongo.java: INFO
